language: rust

matrix:
  include:

    # MSRV: Minimum Supported Rust Version
    - env: TARGET=x86_64-unknown-linux-gnu MSRV=1
      rust: 1.36.0
      if: branch != master

    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable
      if: branch != master

    # does not support atomic loads
    - env: TARGET=riscv32imc-unknown-none-elf
      rust: stable
      if: branch != master

    # build docs on master
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    - env: TARGET=armv7r-none-eabi
      rust: nightly
      if: branch != master

    - env: TARGET=thumbv6m-none-eabi
      rust: nightly
      if: branch != master

    - env: TARGET=thumbv7m-none-eabi
      rust: nightly
      if: branch != master

    - env: TARGET=thumbv8m.base-none-eabi
      rust: nightly
      if: branch != master

    - env: TARGET=thumbv8m.main-none-eabi
      rust: nightly
      if: branch != master

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

after_success:
  - bash ci/after_success.sh

cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
