language: rust

matrix:
  include:
    # TODO MSRV
    # - env: TARGET=x86_64-unknown-linux-gnu
    #   rust: 1.36.0
    #   if: branch != master

    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

    - env: TARGET=thumbv6m-none-eabi
      rust: nightly
      if: branch != master

    - env: TARGET=thumbv7m-none-eabi
      rust: nightly
      if: branch != master

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

after_success:
  - bash ci/after_success.sh

cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
